### ISSUE TITLE
Can't click next chapter

### ISSUE THREAD

**Issue by jeffsabarman** [CryptozombiesHQ/cryptozombie-lessons#663]
Hello Loom Team! There seems to be an issue when click to the next chapter, it just stays in the current chapter. So the only way to move on to the next chapter is to manually change the chapter number in URL params

**Comment by andreipope** [comment]
Hey @jeffsabarman
Please disable any extensions that might interfere with JavaScript, or log out and log in again. If the problem persists, please post a short a screenshot of your browser’s JavaScript console.
Thank you.

**Comment by WillowWisp** [comment]
`Sign out => sign in` solved the problem for me so maybe there's something corrupted in the storage.

**Comment by RishiMalhotra920** [comment]
I signed in to the account from multiple devices (multiple browser sessions). Sign out => sign in fixed it.

**Comment by akash-shrestha** [comment]
Change the chapter number in the web address bar of you browser and hit enter
