### ISSUE TITLE
Isn't working on Brave Browser

### ISSUE THREAD

**Issue by m3rvan** [CryptozombiesHQ/cryptozombie-lessons#691]
After opening the website and clicking 'Get Started', I can see only the background and there aren't anything to click or interact. When I try to open cryptozombies in Edge, it works normally.
![asdas](https://user-images.githubusercontent.com/67842466/183446373-389b386b-3bf5-4443-b26f-544550fdf971.png)

**Comment by taylorferran** [comment]
Same happened with me in Brave, here's some console debug I see when I try to load the page, in case it helps anyone:

![image](https://user-images.githubusercontent.com/45994626/184115310-18d22f5b-38fc-49ec-af25-938c1adb2f6b.png)

**Comment by lonasozo** [comment]
Same problem here, if you run "private mode" it should work. 

On Brave I get the same error reported from @taylorferran: 
![image](https://user-images.githubusercontent.com/34058834/184478176-32485684-2e82-4dab-af01-ddcf8545e91e.png)

Formatted the file and console set this as error: 
![image](https://user-images.githubusercontent.com/34058834/184478206-1f9fa712-254d-4bd7-b325-14c4bbc1a78e.png)

**Comment by 84matte84** [comment]
Same issue...not working on Brave! Please fix it.

**Comment by MajorTom327** [comment]
Just finished chapter-1 to chapter-6
So it seem to work now.

**Comment by andreipope** [comment]
Going to close this ticket as we cannot reproduce the issue.
