### ISSUE TITLE
Lesson 3, Chapter 9: Might be nice to have the reminder of code checker limitations again

### ISSUE THREAD

**Issue by kaleblub** [CryptozombiesHQ/cryptozombie-lessons#695]
In Lesson 3(Advanced Solidity Concepts), Chapter 9(Zombie Modifiers), it is easy to forget to put the "msg.sender" first in the require statements, but as was stated in previous lessons and chapters, it is okay to put either first, but for the limitations of the code checker, the "msg.sender" should be first.
If users forget that specific requirement, we have no choice but to click "Show me the answer"... Even though technically, we got the answer right.
So I think it would be nice to have that small reminder again.

**Comment by dns7030** [comment]
Also starting almost from the beginning of the lesson the code checker requires not following as copied from earlier lesson:

  oracleContract.events.SetLatestEthPriceEvent(async (err, event) => {
    if (err) {
      console.error('Error on event', err)
      return
    }
    // Do something
  })

but

  oracleContract.events.SetLatestEthPriceEvent(async (err, event) => {
    if (err)   console.error('Error on event', err)
      
  
    // Do something
  })

**Comment by andreipope** [comment]
@kaleblub Please feel free to raise a PR against this repo. We'll be happy to review and merge it.
