### ISSUE TITLE
Login does not work anymore

### ISSUE THREAD

**Issue by iggyzap** [CryptozombiesHQ/cryptozombie-lessons#712]
When I cleared out cache and logged out and tried to log back in, following error is displayed in console:

```
XMLHttpRequest cannot load https://share.cryptozombies.io/auth/login due to access control checks.
```
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/4525023/210609939-23be0c8f-581f-40b9-a0b6-9623a6b11493.png">

**Comment by andreipope** [comment]
Hey,

Please disable any extensions that might interfere with JavaScript, or log out and log in again. Let us know if this fixes the issue.

Thank you.

**Comment by rypback** [comment]
I'm also experiencing this. I've disabled all of my extensions and no luck on my end. This is a brand new account, and I've never gotten login to work, so I've got nothing to log out of.

<img width="754" alt="Screenshot 2023-01-04 at 11 47 20 PM" src="https://user-images.githubusercontent.com/108766404/210728497-e6737830-379a-4d0f-aaed-2044ed31e2f9.png">

<img width="608" alt="Screenshot 2023-01-04 at 11 47 53 PM" src="https://user-images.githubusercontent.com/108766404/210728453-3d15206e-c210-4171-b5ad-cd1080b3051a.png">

Thank you

**Comment by segurvita** [comment]
I cannot log in either.

I am getting the following CORS policy error.

> Access to XMLHttpRequest at 'https://share.cryptozombies.io/auth/login' from origin 'https://cryptozombies.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> TypeError: Cannot read properties of undefined (reading 'data')
    at mO.<anonymous> (app.91185cd5f307ae983c53.bundle.js:2:3278538)
    at app.91185cd5f307ae983c53.bundle.js:2:3276406
    at Object.throw (app.91185cd5f307ae983c53.bundle.js:2:3276511)
    at s (app.91185cd5f307ae983c53.bundle.js:2:3275288)

> POST https://share.cryptozombies.io/auth/login net::ERR_FAILED

**Comment by iggyzap** [comment]
> Hey, Please disable any extensions that might interfere with JavaScript, or log out and log in again. Let us know if this fixes the issue. Thank you.
> […](#)

I don't have any extensions that interfere with JS, plus I've got error from above _after_ I logged out and tried to log back in.

**Comment by slobodan-ilic** [comment]
I can't log in either. Tried disabling all extensions, still no luck.

**Comment by sanshigo345** [comment]
I can't log in for a day now. Disables all extensions, used different browsers.

**Comment by andreipope** [comment]
Our engineers are investigating an issue that's preventing login from working. We'll keep you posted. Sorry for any inconvenience this caused.

**Comment by andreipope** [comment]
The issue that has prevented users from logging in has been resolved. Thank you all for being patient.

**Comment by segurvita** [comment]
Thanks for the quick resolution!

**Comment by iggyzap** [comment]
Thank you, confirming it's resolved.

**Comment by slobodan-ilic** [comment]
Thanks, works now!
