### ISSUE TITLE
I selected Japanese in the language settings, but some notations are displayed in Korean.

### ISSUE THREAD

**Issue by segurvita** [CryptozombiesHQ/cryptozombie-lessons#713]
I selected Japanese in the language settings, but some notations are displayed in Korean.

The red line in the figure shows Korean.
![image](https://user-images.githubusercontent.com/4960850/210754901-9a6ba4dc-235f-4bdc-a306-b2b6518e0115.png)

For example, `챕터 1` is Korean, not Japanese. The correct Japanese is `チャプター 1`.

I think that "ko/index.json" is being enabled instead of "jp/index.json" in some words.

## jp/index.json

I checked https://github.com/CryptozombiesHQ/cryptozombie-lessons/blob/master/jp/index.json and found the following code.

```json
"chapter": "チャプター {chapterNum}",
```

This string `チャプター` is correct Japanese.

## ko/index.json

I checked https://github.com/CryptozombiesHQ/cryptozombie-lessons/blob/master/ko/index.json and found the following code.

```json
"chapter": "챕터 {chapterNum}",
```

This string `챕터` is correct Korean.

**Comment by andreipope** [comment]
@segurvita Hey, thanks for pointing this out. Please raise a PR against this repo, and we'll be happy to review and merge it.
