### ISSUE TITLE
Can't switch to th next chapter.

### ISSUE THREAD

**Issue by vdRobin** [CryptozombiesHQ/cryptozombie-lessons#728]
Hello to all !

I don't know why but I can't switch to the next chapter, so each time I click on next chapter, the page is just reloading with an 403 error.
To switch between chapter, I just change the chapter in the URL.

Best Regards,

**Comment by andreipope** [comment]
Hey, try to disable any extensions that might interfere with JavaScript, or log out and log in again. If the problem persists, please post a screenshot of your browser’s JavaScript console

**Comment by MikeMatovu** [comment]
Had the same issue, solved it by logging out and then logging in again
