### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by KalyaniDhok** [CryptozombiesHQ/cryptozombie-lessons#734]
I tried logging in to cryptozombies, it showed the below error:
![image](https://user-images.githubusercontent.com/11286979/219855685-6b37ea83-ccf3-4f20-bebd-87b99cd499fc.png)

**Comment by andreipope** [comment]
Hey, try to disable any extensions that might interfere with JavaScript, and log out and log in again. Let us know if this solves the issue.
