### ISSUE TITLE
Not moving to next chapter after completing previous chapter

### ISSUE THREAD

**Issue by egba001** [CryptozombiesHQ/cryptozombie-lessons#758]
After completing a chapter and click on the next button to move the next chapter, the page synchronizes for a while but remains on the same page after synchronizing

**Comment by andreipope** [comment]
We cannot reproduce the issue. Please turn off any extensions that might interfere with JS, such as ad-blockers. If the problem persists, please provide a screenshot of your JS console showing the relevant error.
