### ISSUE TITLE
Wrong typo for Lesson 16 chapter 9

### ISSUE THREAD

**Issue by hovanhoa** [CryptozombiesHQ/cryptozombie-lessons#764]
<img width="825" alt="Screenshot 2023-12-14 at 14 06 45" src="https://github.com/CryptozombiesHQ/cryptozombie-lessons/assets/56647826/2bf16c1f-3530-408c-a04c-e806887c94c8">

**Comment by andreipope** [comment]
Thanks for reporting this issue. It has been fixed.
